"""Added new field for Tickets as a note

Revision ID: fd8c7337cacf
Revises: a6ca89ea0f4e
Create Date: 2024-05-29 17:43:51.716904

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fd8c7337cacf'
down_revision = 'a6ca89ea0f4e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ticket', schema=None) as batch_op:
        batch_op.add_column(sa.Column('note', sa.Text(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ticket', schema=None) as batch_op:
        batch_op.drop_column('note')

    # ### end Alembic commands ###
